version: '3.3'

networks:
  nginx_net:
    driver: bridge

services:

  webcalculadora:
    build:
      context: ./calculadora
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    networks:
      - nginx_net

  crud:
    build: 
      context: ./Crud_Html_CSS_JS
      dockerfile: Dockerfile
    ports:
      - "8084:80"
    networks:
      - nginx_net

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_net

  webcolorblue:
    image: fabricioveronez/web-color:blue
    ports:
      - "8081:80"
    networks:
      - nginx_net
      
  webcolorgreen:
    image: fabricioveronez/web-color:green
    # ports:
    #   - "8082:80"
    networks:
      - nginx_net

